export enum GROUP {
  MODEL = "MODEL_GROUP",
  HELPER = "HELPER_GROUP",
  MARK_LABEL = "MARK_LABEL_GROUP",
  LIGHT = "LIGHT_GROUP",
  GEOMETRY = "GEOMETRY_GROUP",
  BOX = "BOX_HELPER",
  ENV = "_ENV_",
  ROAM = "_ROAM_",
  TEST = "TEST_GROUP",
  NONE = "NONE",
}
