export const GLOBAL_CONSTANT = {
  MODEL_GROUP: "MODEL_GROUP",
  HELPER_GROUP: "HELPER_GROUP",
  MARK_LABEL_GROUP: "MARK_LABEL_GROUP",
  LIGHT_GROUP: "LIGHT_GROUP",
  GEOMETRY_GROUP: "GEOMETRY_GROUP",
  BOX_HELPER: "BOX_HELPER",
  _ENV_: "_ENV_",
  _ROAM_: "_ROAM_",
};
export enum GROUP {
  MODEL = "MODEL_GROUP",
  HELPER = "HELPER_GROUP",
  MARK_LABEL = "MARK_LABEL_GROUP",
  LIGHT = "LIGHT_GROUP",
  GEOMETRY = "GEOMETRY_GROUP",
  BOX = "BOX_HELPER",
  _ENV_ = "_ENV_",
  _ROAM_ = "_ROAM_",
}
