/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const Editor3dIndexLazyRouteImport = createFileRoute('/editor3d/')()
const Editor3dTestLazyRouteImport = createFileRoute('/editor3d/test')()
const Editor3dScriptLazyRouteImport = createFileRoute('/editor3d/script')()
const Editor3dPreViewLazyRouteImport = createFileRoute('/editor3d/preView')()
const Editor3dModelLazyRouteImport = createFileRoute('/editor3d/model')()
const Editor3dMeshLazyRouteImport = createFileRoute('/editor3d/mesh')()
const Editor3dMarkLazyRouteImport = createFileRoute('/editor3d/mark')()
const Editor3dExtendLazyRouteImport = createFileRoute('/editor3d/extend')()
const Editor3dEffectsLazyRouteImport = createFileRoute('/editor3d/effects')()
const Editor3dDocumentLazyRouteImport = createFileRoute('/editor3d/document')()
const Editor3dConfigLazyRouteImport = createFileRoute('/editor3d/config')()
const Editor3dAboutLazyRouteImport = createFileRoute('/editor3d/about')()

const Editor3dIndexLazyRoute = Editor3dIndexLazyRouteImport.update({
  id: '/editor3d/',
  path: '/editor3d/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/index.lazy').then((d) => d.Route),
)
const Editor3dTestLazyRoute = Editor3dTestLazyRouteImport.update({
  id: '/editor3d/test',
  path: '/editor3d/test',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/editor3d/test.lazy').then((d) => d.Route))
const Editor3dScriptLazyRoute = Editor3dScriptLazyRouteImport.update({
  id: '/editor3d/script',
  path: '/editor3d/script',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/script.lazy').then((d) => d.Route),
)
const Editor3dPreViewLazyRoute = Editor3dPreViewLazyRouteImport.update({
  id: '/editor3d/preView',
  path: '/editor3d/preView',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/preView.lazy').then((d) => d.Route),
)
const Editor3dModelLazyRoute = Editor3dModelLazyRouteImport.update({
  id: '/editor3d/model',
  path: '/editor3d/model',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/model.lazy').then((d) => d.Route),
)
const Editor3dMeshLazyRoute = Editor3dMeshLazyRouteImport.update({
  id: '/editor3d/mesh',
  path: '/editor3d/mesh',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/editor3d/mesh.lazy').then((d) => d.Route))
const Editor3dMarkLazyRoute = Editor3dMarkLazyRouteImport.update({
  id: '/editor3d/mark',
  path: '/editor3d/mark',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/editor3d/mark.lazy').then((d) => d.Route))
const Editor3dExtendLazyRoute = Editor3dExtendLazyRouteImport.update({
  id: '/editor3d/extend',
  path: '/editor3d/extend',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/extend.lazy').then((d) => d.Route),
)
const Editor3dEffectsLazyRoute = Editor3dEffectsLazyRouteImport.update({
  id: '/editor3d/effects',
  path: '/editor3d/effects',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/effects.lazy').then((d) => d.Route),
)
const Editor3dDocumentLazyRoute = Editor3dDocumentLazyRouteImport.update({
  id: '/editor3d/document',
  path: '/editor3d/document',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/document.lazy').then((d) => d.Route),
)
const Editor3dConfigLazyRoute = Editor3dConfigLazyRouteImport.update({
  id: '/editor3d/config',
  path: '/editor3d/config',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/config.lazy').then((d) => d.Route),
)
const Editor3dAboutLazyRoute = Editor3dAboutLazyRouteImport.update({
  id: '/editor3d/about',
  path: '/editor3d/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/editor3d/about.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/editor3d/about': typeof Editor3dAboutLazyRoute
  '/editor3d/config': typeof Editor3dConfigLazyRoute
  '/editor3d/document': typeof Editor3dDocumentLazyRoute
  '/editor3d/effects': typeof Editor3dEffectsLazyRoute
  '/editor3d/extend': typeof Editor3dExtendLazyRoute
  '/editor3d/mark': typeof Editor3dMarkLazyRoute
  '/editor3d/mesh': typeof Editor3dMeshLazyRoute
  '/editor3d/model': typeof Editor3dModelLazyRoute
  '/editor3d/preView': typeof Editor3dPreViewLazyRoute
  '/editor3d/script': typeof Editor3dScriptLazyRoute
  '/editor3d/test': typeof Editor3dTestLazyRoute
  '/editor3d': typeof Editor3dIndexLazyRoute
}
export interface FileRoutesByTo {
  '/editor3d/about': typeof Editor3dAboutLazyRoute
  '/editor3d/config': typeof Editor3dConfigLazyRoute
  '/editor3d/document': typeof Editor3dDocumentLazyRoute
  '/editor3d/effects': typeof Editor3dEffectsLazyRoute
  '/editor3d/extend': typeof Editor3dExtendLazyRoute
  '/editor3d/mark': typeof Editor3dMarkLazyRoute
  '/editor3d/mesh': typeof Editor3dMeshLazyRoute
  '/editor3d/model': typeof Editor3dModelLazyRoute
  '/editor3d/preView': typeof Editor3dPreViewLazyRoute
  '/editor3d/script': typeof Editor3dScriptLazyRoute
  '/editor3d/test': typeof Editor3dTestLazyRoute
  '/editor3d': typeof Editor3dIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/editor3d/about': typeof Editor3dAboutLazyRoute
  '/editor3d/config': typeof Editor3dConfigLazyRoute
  '/editor3d/document': typeof Editor3dDocumentLazyRoute
  '/editor3d/effects': typeof Editor3dEffectsLazyRoute
  '/editor3d/extend': typeof Editor3dExtendLazyRoute
  '/editor3d/mark': typeof Editor3dMarkLazyRoute
  '/editor3d/mesh': typeof Editor3dMeshLazyRoute
  '/editor3d/model': typeof Editor3dModelLazyRoute
  '/editor3d/preView': typeof Editor3dPreViewLazyRoute
  '/editor3d/script': typeof Editor3dScriptLazyRoute
  '/editor3d/test': typeof Editor3dTestLazyRoute
  '/editor3d/': typeof Editor3dIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/editor3d/about'
    | '/editor3d/config'
    | '/editor3d/document'
    | '/editor3d/effects'
    | '/editor3d/extend'
    | '/editor3d/mark'
    | '/editor3d/mesh'
    | '/editor3d/model'
    | '/editor3d/preView'
    | '/editor3d/script'
    | '/editor3d/test'
    | '/editor3d'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/editor3d/about'
    | '/editor3d/config'
    | '/editor3d/document'
    | '/editor3d/effects'
    | '/editor3d/extend'
    | '/editor3d/mark'
    | '/editor3d/mesh'
    | '/editor3d/model'
    | '/editor3d/preView'
    | '/editor3d/script'
    | '/editor3d/test'
    | '/editor3d'
  id:
    | '__root__'
    | '/editor3d/about'
    | '/editor3d/config'
    | '/editor3d/document'
    | '/editor3d/effects'
    | '/editor3d/extend'
    | '/editor3d/mark'
    | '/editor3d/mesh'
    | '/editor3d/model'
    | '/editor3d/preView'
    | '/editor3d/script'
    | '/editor3d/test'
    | '/editor3d/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Editor3dAboutLazyRoute: typeof Editor3dAboutLazyRoute
  Editor3dConfigLazyRoute: typeof Editor3dConfigLazyRoute
  Editor3dDocumentLazyRoute: typeof Editor3dDocumentLazyRoute
  Editor3dEffectsLazyRoute: typeof Editor3dEffectsLazyRoute
  Editor3dExtendLazyRoute: typeof Editor3dExtendLazyRoute
  Editor3dMarkLazyRoute: typeof Editor3dMarkLazyRoute
  Editor3dMeshLazyRoute: typeof Editor3dMeshLazyRoute
  Editor3dModelLazyRoute: typeof Editor3dModelLazyRoute
  Editor3dPreViewLazyRoute: typeof Editor3dPreViewLazyRoute
  Editor3dScriptLazyRoute: typeof Editor3dScriptLazyRoute
  Editor3dTestLazyRoute: typeof Editor3dTestLazyRoute
  Editor3dIndexLazyRoute: typeof Editor3dIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor3d/': {
      id: '/editor3d/'
      path: '/editor3d'
      fullPath: '/editor3d'
      preLoaderRoute: typeof Editor3dIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/test': {
      id: '/editor3d/test'
      path: '/editor3d/test'
      fullPath: '/editor3d/test'
      preLoaderRoute: typeof Editor3dTestLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/script': {
      id: '/editor3d/script'
      path: '/editor3d/script'
      fullPath: '/editor3d/script'
      preLoaderRoute: typeof Editor3dScriptLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/preView': {
      id: '/editor3d/preView'
      path: '/editor3d/preView'
      fullPath: '/editor3d/preView'
      preLoaderRoute: typeof Editor3dPreViewLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/model': {
      id: '/editor3d/model'
      path: '/editor3d/model'
      fullPath: '/editor3d/model'
      preLoaderRoute: typeof Editor3dModelLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/mesh': {
      id: '/editor3d/mesh'
      path: '/editor3d/mesh'
      fullPath: '/editor3d/mesh'
      preLoaderRoute: typeof Editor3dMeshLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/mark': {
      id: '/editor3d/mark'
      path: '/editor3d/mark'
      fullPath: '/editor3d/mark'
      preLoaderRoute: typeof Editor3dMarkLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/extend': {
      id: '/editor3d/extend'
      path: '/editor3d/extend'
      fullPath: '/editor3d/extend'
      preLoaderRoute: typeof Editor3dExtendLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/effects': {
      id: '/editor3d/effects'
      path: '/editor3d/effects'
      fullPath: '/editor3d/effects'
      preLoaderRoute: typeof Editor3dEffectsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/document': {
      id: '/editor3d/document'
      path: '/editor3d/document'
      fullPath: '/editor3d/document'
      preLoaderRoute: typeof Editor3dDocumentLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/config': {
      id: '/editor3d/config'
      path: '/editor3d/config'
      fullPath: '/editor3d/config'
      preLoaderRoute: typeof Editor3dConfigLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor3d/about': {
      id: '/editor3d/about'
      path: '/editor3d/about'
      fullPath: '/editor3d/about'
      preLoaderRoute: typeof Editor3dAboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Editor3dAboutLazyRoute: Editor3dAboutLazyRoute,
  Editor3dConfigLazyRoute: Editor3dConfigLazyRoute,
  Editor3dDocumentLazyRoute: Editor3dDocumentLazyRoute,
  Editor3dEffectsLazyRoute: Editor3dEffectsLazyRoute,
  Editor3dExtendLazyRoute: Editor3dExtendLazyRoute,
  Editor3dMarkLazyRoute: Editor3dMarkLazyRoute,
  Editor3dMeshLazyRoute: Editor3dMeshLazyRoute,
  Editor3dModelLazyRoute: Editor3dModelLazyRoute,
  Editor3dPreViewLazyRoute: Editor3dPreViewLazyRoute,
  Editor3dScriptLazyRoute: Editor3dScriptLazyRoute,
  Editor3dTestLazyRoute: Editor3dTestLazyRoute,
  Editor3dIndexLazyRoute: Editor3dIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
